FROM piece-base:latest

WORKDIR /app/apps/backend/piece

EXPOSE 3100

HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://127.0.0.1:3100/health || exit 1

CMD ["node", "src/index.js"]
