export const SCREENPLAY_PAGE_WIDTH_PX = 816
export const SCREENPLAY_PAGE_HEIGHT_PX = 1056

export const SCREENPLAY_PAGE_PADDING_TOP_PX = 96
export const SCREENPLAY_PAGE_PADDING_RIGHT_PX = 96
export const SCREENPLAY_PAGE_PADDING_BOTTOM_PX = 96
export const SCREENPLAY_PAGE_PADDING_LEFT_PX = 144

export const SCREENPLAY_FONT_SIZE_PX = 16
export const SCREENPLAY_LINE_HEIGHT_PX = 16

export const SCREENPLAY_OVERLAY_PAGE_ZOOM = 1.04

export const SCREENPLAY_TEXT_AREA_HEIGHT_PX =
  SCREENPLAY_PAGE_HEIGHT_PX -
  SCREENPLAY_PAGE_PADDING_TOP_PX -
  SCREENPLAY_PAGE_PADDING_BOTTOM_PX

// Final Draft standard: 864px text area / 16px line-height = 54 lines per page.
export const SCREENPLAY_LINES_PER_PAGE = 54

export const SCREENPLAY_CHARACTER_INDENT_CH = 24
export const SCREENPLAY_DIALOGUE_INDENT_LEFT_CH = 11
export const SCREENPLAY_DIALOGUE_INDENT_RIGHT_CH = 11
export const SCREENPLAY_PARENTHETICAL_INDENT_CH = 18

export const SCREENPLAY_SCENE_HEADING_MARGIN_TOP_PX = 24
export const SCREENPLAY_CHARACTER_MARGIN_TOP_PX = 24
export const SCREENPLAY_TRANSITION_MARGIN_TOP_PX = 24
export const SCREENPLAY_ACTION_AFTER_ACTION_MARGIN_TOP_PX = 16
export const SCREENPLAY_ACTION_AFTER_SCENE_HEADING_MARGIN_TOP_PX = 16

export const SCREENPLAY_PAGE_GAP_PX = 24

export const SCREENPLAY_EDITOR_PADDING = `${SCREENPLAY_PAGE_PADDING_TOP_PX}px ${SCREENPLAY_PAGE_PADDING_RIGHT_PX}px ${SCREENPLAY_PAGE_PADDING_BOTTOM_PX}px ${SCREENPLAY_PAGE_PADDING_LEFT_PX}px`